struct hello {
    x: int32,
    y: int32
}

trait hell {
    func newhell() -> int32 {
        //return 0;
        var x: int32;
        //if x == (1 as int32) {
        //    return x+(1 as int32);
        //} else {
        //    return x+(2 as int32);
        //}
        return if x == (1 as int32) {
            x+(1 as int32);
        } else {
            x+(2 as int32);
        }
    }
}

impl hello {
    func new(y: int32) -> int32 {
        return y;
    }

    func new2() -> int32 {
        return (10 as int32);
    }
}

impl hell for hello {
    func newhell() -> int32 {
        return (20 as int32);
    }
}

func main2() -> int64 {
    //return (10 as int32);
    return 10;
}

func main() -> int64  {
    //a = 20 as int32, 10 as int64;
    //x.b.c(a, b);
    //a = x.b();
    //if b {} else {}
    //for x = 10; x<10;x*=2 {  }
    
    //var x: int32 = 0;
    //var y: int32 = 1;
    //var z = (x + y);
    //if z == (x+y) {}
    
    var y: int32;
    var z: int32;
    y = 10 as int32;
    var x: hello = hello{x: y, y: z};
    //x = hello{x: y, y: z};
    x.x = 10 as int32;
    x.new(y);
    main2();
    return 10;
    
    
    
    //x.x = 10;
    //x.y;
    //var y: int32;
    //var z: int32;
    //var a: int32;
    //a = 10;
    //a = y+z;
    //a += y;

    //main2();
    //a = y + z;
    //for (x.x as int64) == 10 {}
}