#[allow(non_camel_case_types,dead_code)]
#[derive(Debug,PartialEq,Clone)]
pub enum TokenType {
    ERROR,

    // keywords
    K_VAR, K_STRUCT, K_IMPL, K_FUNC, K_OR, K_AND, K_IF, K_ELSE, K_FOR,
    K_RETURN, /* K_SELF */

    // datatypes
    K_INT8, K_INT16, K_INT32, K_INT64,
    K_UINT8, K_UINT16, K_UINT32, K_UINT64,
    K_FLOAT32, K_FLOAT64, K_BOOL, OBJECT_TYPE,
    K_NULL,

    K_TRUE, K_FALSE,

    IDENTIFIER, 

    INT_LITERAL, HEX_LITERAL, OCTAL_LITERAL, STRING_LITERAL, 
    SEMICOLON, COMMA, DOT,

    // operators
    PLUS, PLUS_EQUAL,
    MINUS, MINUS_EQUAL,
    ASTERISK, ASTERISK_EQUAL,
    SLASH, SLASH_EQUAL,
    MOD, MOD_EQUAL,
    EQUAL, EQUAL_EQUAL,
    BANG, BANG_EQUAL,
    CURLY_OPEN, CURLY_CLOSE,
    BRACKET_OPEN, BRACKET_CLOSE,
    SQUARE_OPEN, SQUARE_CLOSE,
    LESS_THAN, LESS_EQUAL,
    GREAT_THAN, GREAT_EQUAL,
    BITWISE_XOR, BITWISE_XOR_EQUAL,
    BITWISE_AND, BITWISE_AND_EQUAL,
    BITWISE_OR, BITWISE_OR_EQUAL,
    DOLLAR, HASH,

    FILE_EOF
}